spring.application.name=Backend

spring.datasource.hikari.data-source-properties.sslMode=REQUIRED
spring.datasource.url=jdbc:mysql://mysql-3885ff36-khageswararaor-24.c.aivencloud.com:19452/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_dYiIJtacAD189jw55JS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
server.address=0.0.0.0

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khageswararaor@gmail.com
spring.mail.password=vybi hrtn qihj tols

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

